name: Java CI with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      # Usa la acción para configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Ejecuta los tests (tenemos unitatrios y de integracion juntos)
      - name: Test with Gradle
        run: cd demo && ./gradlew test

      # Ejecuta Checkstyle para verificar el estilo del código de los test y del main
      - name: Run Checkstyle
        run: cd demo && ./gradlew checkstyleMain checkstyleTest

      # Ejecuta el comando para compilar el proyecto
      - name: Build with Gradle
        run: cd demo && ./gradlew build